apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-config
data:
  config.json: |
    {"tokens":{"AccessToken":"insertaccesstoken"}, "tags":{"Env":"k8s", "KubernetesCluster":"insertkubernetesclusterhere"}, "serverurl":"https://api.lacework.net"}
